# Generated by Django 4.2.7 on 2023-11-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Concrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abstract_field", models.CharField(max_length=256)),
                ("concrete_field", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256, null=True)),
                ("last_name", models.CharField(max_length=256, null=True)),
                ("age", models.IntegerField(null=True)),
                ("number", models.IntegerField(null=True)),
                ("timestamp", models.DateTimeField(null=True)),
                (
                    "children",
                    models.ManyToManyField(related_name="examples", to="example.child"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Far",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Total",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totals",
                        to="example.example",
                    ),
                ),
                (
                    "far",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total",
                        to="example.far",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "example",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thing",
                        to="example.example",
                    ),
                ),
                (
                    "far",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thing",
                        to="example.far",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "examples",
                    models.ManyToManyField(related_name="parts", to="example.example"),
                ),
                (
                    "far",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part",
                        to="example.far",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="example",
            name="other",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examples",
                to="example.other",
            ),
        ),
        migrations.AddField(
            model_name="example",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="example",
                to="example.question",
            ),
        ),
    ]
