# Generated by Django 5.0.2 on 2024-02-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnotherConcrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abstract_field", models.CharField(max_length=256)),
                ("another_abstract_field", models.CharField(max_length=256)),
                ("another_concrete_field", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Concrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abstract_field", models.CharField(max_length=256)),
                ("concrete_field", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Far",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("number", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256, null=True)),
                ("last_name", models.CharField(max_length=256, null=True)),
                ("age", models.IntegerField(null=True)),
                ("number", models.IntegerField(null=True)),
                ("timestamp", models.DateTimeField(null=True)),
                (
                    "children",
                    models.ManyToManyField(related_name="examples", to="example.child"),
                ),
                (
                    "other",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="example.other",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example",
                        to="example.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("number", models.IntegerField(null=True)),
                (
                    "examples",
                    models.ManyToManyField(related_name="parts", to="example.example"),
                ),
                (
                    "far",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="example.far",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("number", models.IntegerField(null=True)),
                (
                    "parts",
                    models.ManyToManyField(related_name="aliens", to="example.part"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("number", models.IntegerField(null=True)),
                (
                    "aliens",
                    models.ManyToManyField(related_name="things", to="example.alien"),
                ),
                (
                    "example",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thing",
                        to="example.example",
                    ),
                ),
                (
                    "far",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thing",
                        to="example.far",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Total",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("number", models.IntegerField(null=True)),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totals",
                        to="example.example",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="far",
            name="total",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="far",
                to="example.total",
            ),
        ),
        migrations.AddField(
            model_name="alien",
            name="total",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliens",
                to="example.total",
            ),
        ),
    ]
