site_name: Django Lookup Property
site_description: Django model properties that are also lookup expressions.

nav:
  - Home: index.md
  - Introduction: intro.md
  - Usage: usage.md
  - Converters: converters.md

theme:
  name: readthedocs
  highlightjs: false  # Use pygments instead.

markdown_extensions:
  pymdownx.highlight:
    anchor_linenums: true
    linenums: true
  pymdownx.inlinehilite:
  pymdownx.blocks.details:
  pymdownx.snippets:
    base_path: docs/snippets
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid
  toc:
    permalink: 🔗
  attr_list:
  meta:

plugins:
  - search:
  - mermaid2:
      version: 11.6.0

extra_css:
  - css/docs.css
  - css/pygments.css
