[project]
name = "django-lookup-property"
version = "0.2.2"
description = "Django model properties that are also lookup expressions."
authors = [
    { name = "Matti Lamppu", email = "lamppu.matti.akseli@gmail.com" },
]
license = "MIT"
readme = "README.md"
keywords = [
    "django",
    "lookup",
    "property",
    "orm",
    "model",
    "extension",
]
classifiers = [
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
]
requires-python = ">=3.11,<4"
dynamic = [
    "dependencies",
]

[project.urls]
"Homepage" = "https://mrthearman.github.io/django-lookup-property"
"Repository" = "https://github.com/MrThearMan/django-lookup-property"
"Bug Tracker" = "https://github.com/MrThearMan/django-lookup-property/issues"
"Documentation" = "https://mrthearman.github.io/django-lookup-property"

[tool.poetry]
requires-poetry = ">=2.0.0"
packages = [
    { include = "lookup_property" },
]

[tool.poetry.dependencies]
Django = ">=5.2.17"

[tool.poetry.group.test.dependencies]
pytest = "9.1.1"
pytest-django = "4.14.0"
coverage = "7.16.2"
freezegun = "1.5.5"
nox = "2026.8.17"
factory-boy = "3.3.3"

[tool.poetry.group.docs.dependencies]
mkdocs = "1.6.1"
pymdown-extensions = "12.1"
mkdocs-mermaid2-plugin = "1.2.3"

[tool.poetry.group.lint.dependencies]
pre-commit = "4.6.2"

[tool.django-stubs]
django_settings_module = "example_project.project.settings"

[tool.coverage.run]
relative_files = true

[tool.coverage.report]
omit = [
    "tests/*",
    "docs/*",
    ".venv/*",
    ".tox/*",
]
exclude_lines = [
    "if TYPE_CHECKING:",
    "except ImportError:",
    "pragma: no cover",
    "pass",
    "def __repr__",
    "def __str__",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "example_project.project.settings"
addopts = "--disable-warnings"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
