name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    uses: MrThearMan/CI/.github/workflows/test.yml@v0.3.5
    with:
      python-version: '["3.11", "3.12"]'

